name: simple_search_dropdown_example
description: Demonstrates how to use the simple_search_dropdown plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  simple_search_dropdown:
    path: ../
flutter:
  uses-material-design: true