name: simple_search_dropdown
description: A dropdown that offers a search bar, multiple and single selections.
homepage: https://github.com/Lorenzobettega/searchdropdown

version: 1.7.0

environment:
  sdk: '>=3.0.0 < 4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stringr: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
